### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by saponifi3d**
Upgrades all the dependencies - show stoppers are handlebars 2.0.0 and emblem 0.40.  Fix for https://github.com/buschtoens/gulp-emblem/issues/13

@buschtoens

### CODE REVIEW

**Comment by mattpardee** [comment]
Niiiiiiice. :+1: :+1: :+1:

**Comment by saponifi3d** [comment]
PS - i have verified this all works and matches the same output as `grunt-contrib-handlebars`.

**Comment by buschtoens** [comment]
Thanks a lot. I don't actively work on this repo anymore, as I have moved on to `ember-cli`. Do you want push access?

I'll publish to npm momentarily.

**Comment by saponifi3d** [comment]
Sure - sounds good :D thanks.  (hopefully we can get handlebars@3.0.0 soon)

**Comment by buschtoens** [comment]
Yeah, I'm primarily hoping for HTMLBars support! :D

**Comment by saponifi3d** [comment]
not sure if you'd want to give me access to npm for distro or not .. if you don't mind me bugging you then :dancer: - i was thinking about going back and updating this to use through2 and a few other things. (also want to upgrade emblem to use handlebars 3.0.0)

**Comment by buschtoens** [comment]
If you mind dropping me your npm username, I could add you there as well. ;)

**Comment by saponifi3d** [comment]
:D it's saponifi3d as well. thanks!!

**Comment by buschtoens** [comment]
Consider it done.

**Pull request merged**
